### ISSUE TITLE
Crash in installation

### ISSUE THREAD

**Issue by ghost** [base33/Web-Blocks#7]
I tried installing this on Umbraco 7.1.4 and got the following error message during installation. After this the whole site crashes as well. Any solutions for this?

Could not load types from assembly WebBlocks.Utilities, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null, errors:
Exception: System.TypeLoadException: Method 'get_ContentSet' in type 'WebBlocks.Utilities.Umbraco.DynamicContent' from assembly 'WebBlocks.Utilities, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Exception: System.TypeLoadException: Could not load type 'Umbraco.Core.Models.IPublishedContentProperty' from assembly 'Umbraco.Core, Version=1.0.5261.28127, Culture=neutral, PublicKeyToken=null'.

**Comment by mentordigital** [comment]
Unfortunately, the current release of Mentor Web Blocks does not work 
for Umbraco 7.x.  There is a version being developed for Umbraco 7, but 
this is in the early stages.

The Umbraco 6 version works with the latest Umbraco 6, and is still 
running fine and is still supported.

Thanks,

Craig

On 01/12/2014 14:48, petersaverman wrote:

> I tried installing this on Umbraco 7.1.4 and got the following error 
> message during installation. After this the whole site crashes as 
> well. Any solutions for this?
> 
> Could not load types from assembly WebBlocks.Utilities, 
> Version=1.0.0.0, Culture=neutral, PublicKeyToken=null, errors:
> Exception: System.TypeLoadException: Method 'get_ContentSet' in type 
> 'WebBlocks.Utilities.Umbraco.DynamicContent' from assembly 
> 'WebBlocks.Utilities, Version=1.0.0.0, Culture=neutral, 
> PublicKeyToken=null' does not have an implementation.
> Exception: System.TypeLoadException: Could not load type 
> 'Umbraco.Core.Models.IPublishedContentProperty' from assembly 
> 'Umbraco.Core, Version=1.0.5261.28127, Culture=neutral, 
> PublicKeyToken=null'.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/base33/Mentor-Web-Blocks/issues/7.

## 

_Craig Noble_: Senior Developer
Mentor Digital
T: +44(0)117 305 8900 | E: craig@mentordigital.co.uk 
<3D%22mailto:craig@mentordigital.co.uk%22> | W: www.mentordigital.co.uk 
<3D%22http://www.mentordigital.co.uk/%22>

**Comment by ghost** [comment]
Ah, bummer! Thanks for you fast reply!
